### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by arlyon** [arlyon/litehouse#1]
A lot of this is still in early stages but here is what we have so far:

- [x] basic plugin registry using s3
- [x] basic plugin publishing / searching / fetching 
- [x] ability to fetch / download plugins with local fs caching
- [x] jsonschema based plugin config validation
- [x] plugin loading and subscriptions
- [x] low memory consumption (around 5MB)
- [x] fully sandboxed plugins with server-defined capabilities
- [x] musl based docker container

In progress

- [x] a website! browse plugins, add them to a 'cart' and get a settings file generated for you. see https://litehouse.arlyon.dev/registry for more
- [ ] better registry index. currently we just upload files.
- [ ] better registry publishing. currently you need write access to the bucket and the store is not immutable

Planned

- [ ] a number of plugins
  - matter protocol support
  - mqtt server / client
  - notifications via twilio
  - storing events to sqlite or exporting them via otel
- [ ] plugin types. currently plugins only work over a singe event bus, however I want to support a more imperative API where plugins can declare what operations they support using wit interfaces
- [ ] reactivity. some basic if-this-then-that language for coordinating operations given some preconditions
- [ ] investigate wizer and wasm-opt
